openapi: 3.1.1
info:
  version: next
  title: NHS Notify Supplier API
  description: |
    API for communication suppliers to integrate with NHS Notify.

    This specification represents the in-development 'next' version of the API schema
    and should be treated as unstable.
security:
  - authorization: [ ]
paths:
  /letter:
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    post:
      summary: Update the status of multiple letters
      operationId: postLetter
      tags:
        - letter
    get:
      summary: Get a list of letters
      operationId: getAListOfLetters
      tags:
        - letter
      parameters:
        - $ref: 'components/parameters/letterStatus.yml'
      description: The key use of this endpoint is to query letters which are ready to be printed
      responses:
        '200':
          description: "List of letters to process"
          content:
            application/vnd.api+json:
              schema:
                $ref: 'components/schemas/Letters.yml'
              examples:
                example-1:
                  value:
                    data:
                      - type: Letter
                        id: 2WL5f8j4XVxUPgd3OOqXVYvVFIW
                      - type: Letter
                        id: 2597cg09868HIiofiuiujgneu46
  '/letter/{id}':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
      - $ref: 'components/parameters/resourceId.yml'
    get:
      summary: Retrieve the status of a letter
      description: Get details the status of a letter.
      operationId: get-letter-status
      responses:
        '200':
          description: Letter status
          content:
            application/vnd.api+json:
              schema:
                $ref: 'components/schemas/LetterStatusResponse.yml'
              examples:
                example-1:
                  value:
                    data:
                      type: Letter
                      id: 2WL5f8j4XVxUPgd3OOqXVYvVFIW
                      attributes:
                        status: ACCEPTED
        '404':
          $ref: 'components/responses/ResourceNotFound.yml'
        '429':
          $ref: 'components/responses/TooManyRequests.yml'
        '500':
          $ref: 'components/responses/ServerError.yml'
      tags:
        - letter
    patch:
      summary: Update the status of a letter
      description: Update the status of a letter by providing the new status in the request body.
      operationId: patch-letters
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: 'components/schemas/LetterUpdateRequest.yml'
      responses:
        '200':
          description: Letter resource updated successfully
          content:
            application/vnd.api+json:
              schema:
                $ref: 'components/schemas/LetterStatusResponse.yml'
              examples:
                example-1:
                  value:
                    data:
                      type: Letter
                      id: 2WL5f8j4XVxUPgd3OOqXVYvVFIW
                      attributes:
                        status: ACCEPTED
        '400':
          $ref: 'components/responses/BadRequest.yml'
        '404':
          $ref: 'components/responses/ResourceNotFound.yml'
        '429':
          $ref: 'components/responses/TooManyRequests.yml'
        '500':
          $ref: 'components/responses/ServerError.yml'
      tags:
        - letter
  /mi:
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    get:
      summary: List MI records
      operationId: list-mi
      tags:
        - mi
    post:
      summary: Create a new MI record
      operationId: create-mi
      tags:
        - mi
  '/mi/{id}':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
      - $ref: 'components/parameters/resourceId.yml'
    get:
      summary: Fetch a specific MI record
      operationId: get-mi
      tags:
        - mi
  /specification:
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    get:
      summary: List specifications
      operationId: list-specification
      tags:
        - specification
    post:
      summary: Create a new specification record
      operationId: create-specification
      tags:
        - specification
  '/specification/{id}':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
      - $ref: 'components/parameters/resourceId.yml'
    get:
      summary: Fetch metadata about a specific specification
      operationId: get-specification
      tags:
        - specification
    patch:
      summary: Update metadata about a specific specification
      operationId: patch-specification
      tags:
        - specification
  /proof:
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    get:
      summary: List proof files
      operationId: list-proof
      tags:
        - proof
    post:
      summary: Create a new proof metadata record
      operationId: create-proof
      tags:
        - proof
  '/proof/{id}':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
      - $ref: 'components/parameters/resourceId.yml'
    get:
      summary: Fetch metadata about a specific proof file
      operationId: get-proof
      tags:
        - proof
    patch:
      summary: Update metadata about a specific proof file
      operationId: patch-proof
      tags:
        - proof
  /artwork:
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    post:
      summary: Create a new artwork metadata record
      operationId: create-artwork
      tags:
        - artwork
    get:
      summary: List artwork files
      operationId: list-artwork
      tags:
        - artwork
  '/artwork/{id}':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
      - $ref: 'components/parameters/resourceId.yml'
    get:
      summary: Fetch metadata about a specific artwork file
      operationId: get-artwork
      tags:
        - artwork
    patch:
      summary: Update metadata about a specific artwork file
      operationId: patch-artwork
      tags:
        - artwork
  /whitemail:
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    get:
      summary: List batches of whitemail letters
      operationId: list-whitemail
      tags:
        - whitemail
      x-stoplight:
        id: tpzuuj1eovmtc
    post:
      summary: Create a new whitemail letter batch
      operationId: create-whitemail
      tags:
        - whitemail
      x-stoplight:
        id: wun7ud7savffm
  '/whitemail/{id}':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
      - $ref: 'components/parameters/resourceId.yml'
    get:
      summary: Fetch metadata about a specific whitemail batch
      operationId: get-whitemail
      tags:
        - whitemail
      x-stoplight:
        id: lmbg85kro8iwy

  '/data':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    post:
      summary: Request a URL to upload a new data file
      operationId: post-data
      tags:
        - data

  '/data2/{id}':
    parameters:
      - $ref: 'components/parameters/resourceId.yml'
    get:
      operationId: getdata2

  '/data/{id}':
    parameters:
      - $ref: 'components/parameters/resourceId.yml'

      - name: X-Request-ID
        in: header
        description: 'Unique request identifier, in the format of a GUID'
        required: true
        schema:
          type: string
          examples:
            - dcb9c8dc-c2f4-4d5f-8674-a2e913e040b2

      - name: X-Correlation-ID
        in: header
        description: |-
          An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
          The ID will be returned in a response header.
        required: false
        schema:
          type: string
          examples:
            - 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
    get:
      summary: Fetch a data file
      operationId: get-data-id
      tags:
        - data
      x-stoplight:
        id: 98lwlebl1vxeq
      responses:
        '404':
          description: Not Found
        '303':
          description: See Other
          headers:
            Location:
              schema:
                type: string
              description: The signed S3 URL of the data file to download
    head:
      summary: Fetch data file metadata
      tags:
        - data
      responses:
        200:
          description: OK
      operationId: head-data-id
      x-stoplight:
        id: tdjs72iaaavub
components:
  securitySchemes:
    authorization:
      type: oauth2
      description: |-
        An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication).
        Required in all environments except local and sandbox.
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          scopes: []
tags:
  - name: letter
    description: ''
  - name: specification
    description: ''
  - name: whitemail
    description: ''
  - name: proof
    description: ''
  - name: mi
    description: ''
  - name: artwork
    description: ''
  - name: data
    description: ''
servers:
  - url: 'http://127.0.0.1:3000'
    description: Local development server
  - url: 'https://sandbox-server.nhs.uk/nhs-notify-supplier-api'
    description: Public sandbox
