openapi: 3.0.3
info:
  version: next
  title: NHS Notify Supplier API
  description: |
    API for communication suppliers to integrate with NHS Notify.

    This specification represents the in-development 'next' version of the API schema
    and should be treated as unstable.
security:
  - $ref: 'components/security/security.yml'
paths:
  /letters:
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    post:
      $ref: 'components/endpoints/postLetters.yml'
    get:
      $ref: 'components/endpoints/listLetters.yml'
  '/letters/{id}':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
      - $ref: 'components/parameters/resourceId.yml'
    get:
      $ref: 'components/endpoints/getLetterStatus.yml'
    patch:
      $ref: 'components/endpoints/patchLetter.yml'
  /mi:
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    get:
      $ref: 'components/endpoints/listMI.yml'
    post:
      $ref: 'components/endpoints/createMI.yml'

  '/mi/{id}':
    parameters:
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
      - $ref: 'components/parameters/resourceId.yml'
    get:
      $ref: 'components/endpoints/getMI.yml'

  '/data/{id}':
    parameters:
      - $ref: 'components/parameters/resourceId.yml'
      - $ref: 'components/parameters/requestId.yml'
      - $ref: 'components/parameters/correlationId.yml'
    get:
      $ref: 'components/endpoints/getDataId.yml'
    head:
      $ref: 'components/endpoints/headDataId.yml'
components:
  securitySchemes:
    app-level3:
      $ref: https://proxygen.ptl.api.platform.nhs.uk/components/securitySchemes/app-level3
    app-level0:
      $ref: https://proxygen.ptl.api.platform.nhs.uk/components/securitySchemes/app-level0

tags:
  - name: letter
    description: ''
  - name: mi
    description: ''
  - name: data
    description: ''
servers:
  - url: 'http://127.0.0.1:3000'
    description: Local development server
  - url: 'https://sandbox-server.nhs.uk/nhs-notify-supplier-api'
    description: Public sandbox
x-nhsd-apim:
  temporary: true
  monitoring: false
  access:
    $ref: ./components/x-nhsd-apim/access.yml
  target:
    $ref: ./components/x-nhsd-apim/target.yml
  target-attributes:
    $ref: ./components/x-nhsd-apim/target-attributes.yml
