name: "Build servers"
description: "build servers"
inputs:
  version:
    description: "Version number"
    required: true
  NODE_AUTH_TOKEN:
    description: "Token for access to github package registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 22
        registry-url: 'https://npm.pkg.github.com'

    - name: Npm install
      working-directory: .
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
      run: npm ci
      shell: bash

    - name: make csharp-server folder
      working-directory: ./server
      shell: bash
      run: mkdir csharp-server

    - name: Build servers
      working-directory: ./server
      shell: bash
      run: |
        make build VERSION="${{ inputs.version }}"

    - name: Upload csharp-server artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: "server/csharp-server"
        name: server-csharp-${{ inputs.version }}

    - name: Upload csharp-server docker artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: "server/Dockerfile"
        name: server-csharp-docker-${{ inputs.version }}
