# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.proof_api import ProofApi


class TestProofApi(unittest.TestCase):
    """ProofApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProofApi()

    def tearDown(self) -> None:
        pass

    def test_create_proof(self) -> None:
        """Test case for create_proof

        Create a new proof metadata record
        """
        pass

    def test_get_proof(self) -> None:
        """Test case for get_proof

        Fetch metadata about a specific proof file
        """
        pass

    def test_list_proof(self) -> None:
        """Test case for list_proof

        List proof files
        """
        pass

    def test_patch_proof(self) -> None:
        """Test case for patch_proof

        Update metadata about a specific proof file
        """
        pass


if __name__ == '__main__':
    unittest.main()
