# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.letter_batch_update_data_data_attributes import LetterBatchUpdateDataDataAttributes

class TestLetterBatchUpdateDataDataAttributes(unittest.TestCase):
    """LetterBatchUpdateDataDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LetterBatchUpdateDataDataAttributes:
        """Test LetterBatchUpdateDataDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LetterBatchUpdateDataDataAttributes`
        """
        model = LetterBatchUpdateDataDataAttributes()
        if include_optional:
            return LetterBatchUpdateDataDataAttributes(
                status = 'PENDING',
                reason_code = 1.337,
                reason_text = ''
            )
        else:
            return LetterBatchUpdateDataDataAttributes(
        )
        """

    def testLetterBatchUpdateDataDataAttributes(self):
        """Test LetterBatchUpdateDataDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
