# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.error_data import ErrorData

class TestErrorData(unittest.TestCase):
    """ErrorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorData:
        """Test ErrorData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorData`
        """
        model = ErrorData()
        if include_optional:
            return ErrorData(
                errors = [
                    openapi_client.models.error_item.ErrorItem(
                        id = '', 
                        code = 'CM_NO_BATCH_AVAILABLE', 
                        links = openapi_client.models.error_item_links.ErrorItem_links(
                            about = '', ), 
                        status = '', 
                        title = '', 
                        detail = '', )
                    ]
            )
        else:
            return ErrorData(
        )
        """

    def testErrorData(self):
        """Test ErrorData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
