# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.letter_status import LetterStatus

class TestLetterStatus(unittest.TestCase):
    """LetterStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLetterStatus(self):
        """Test LetterStatus"""
        # inst = LetterStatus()

if __name__ == '__main__':
    unittest.main()
