# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.letter_batch_update_data import LetterBatchUpdateData

class TestLetterBatchUpdateData(unittest.TestCase):
    """LetterBatchUpdateData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LetterBatchUpdateData:
        """Test LetterBatchUpdateData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LetterBatchUpdateData`
        """
        model = LetterBatchUpdateData()
        if include_optional:
            return LetterBatchUpdateData(
                data = openapi_client.models.letter_batch_update_data_data.LetterBatchUpdateData_data(
                    type = null,
                    id = '',
                    attributes = openapi_client.models.letter_batch_update_data_data_attributes.LetterBatchUpdateData_data_attributes(
                        status = 'ACKNOWLEDGED',
                        reason_code = 1.337,
                        reason_text = '', ), )
            )
        else:
            return LetterBatchUpdateData(
        )
        """

    def testLetterBatchUpdateData(self):
        """Test LetterBatchUpdateData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
