# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.batch import Batch

class TestBatch(unittest.TestCase):
    """Batch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Batch:
        """Test Batch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Batch`
        """
        model = Batch()
        if include_optional:
            return Batch(
                status = 'PENDING',
                data = openapi_client.models.data_reference.DataReference(
                    id = '', 
                    sha256 = '', 
                    signature = '', 
                    key = '', ),
                letters = [
                    openapi_client.models.letter.Letter(
                        message_id = '', 
                        file_name = '', 
                        sha256 = '', )
                    ],
                reason_code = 1.337,
                reason_text = ''
            )
        else:
            return Batch(
                status = 'PENDING',
                letters = [
                    openapi_client.models.letter.Letter(
                        message_id = '', 
                        file_name = '', 
                        sha256 = '', )
                    ],
        )
        """

    def testBatch(self):
        """Test Batch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
