# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.error_item_links import ErrorItemLinks

class TestErrorItemLinks(unittest.TestCase):
    """ErrorItemLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorItemLinks:
        """Test ErrorItemLinks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorItemLinks`
        """
        model = ErrorItemLinks()
        if include_optional:
            return ErrorItemLinks(
                about = ''
            )
        else:
            return ErrorItemLinks(
        )
        """

    def testErrorItemLinks(self):
        """Test ErrorItemLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
