# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.production_status import ProductionStatus

class TestProductionStatus(unittest.TestCase):
    """ProductionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductionStatus(self):
        """Test ProductionStatus"""
        # inst = ProductionStatus()

if __name__ == '__main__':
    unittest.main()
