# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.specification_api import SpecificationApi


class TestSpecificationApi(unittest.TestCase):
    """SpecificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpecificationApi()

    def tearDown(self) -> None:
        pass

    def test_create_specification(self) -> None:
        """Test case for create_specification

        Create a new specification record
        """
        pass

    def test_get_specification(self) -> None:
        """Test case for get_specification

        Fetch metadata about a specific specification
        """
        pass

    def test_list_specification(self) -> None:
        """Test case for list_specification

        List specifications
        """
        pass

    def test_patch_specification(self) -> None:
        """Test case for patch_specification

        Update metadata about a specific specification
        """
        pass


if __name__ == '__main__':
    unittest.main()
