# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.batch_api import BatchApi


class TestBatchApi(unittest.TestCase):
    """BatchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BatchApi()

    def tearDown(self) -> None:
        pass

    def test_get_batch_id(self) -> None:
        """Test case for get_batch_id

        Retrieve a batch of letters
        """
        pass

    def test_get_batches(self) -> None:
        """Test case for get_batches

        Retrieve a list of available letter batches
        """
        pass

    def test_patch_letters_batch(self) -> None:
        """Test case for patch_letters_batch

        Update the status of a batch of letters
        """
        pass


if __name__ == '__main__':
    unittest.main()
