# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.letter import Letter

class TestLetter(unittest.TestCase):
    """Letter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Letter:
        """Test Letter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Letter`
        """
        model = Letter()
        if include_optional:
            return Letter(
                message_id = '',
                file_name = '',
                sha256 = ''
            )
        else:
            return Letter(
                message_id = '',
                file_name = '',
                sha256 = '',
        )
        """

    def testLetter(self):
        """Test Letter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
