# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.mi_api import MiApi


class TestMiApi(unittest.TestCase):
    """MiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MiApi()

    def tearDown(self) -> None:
        pass

    def test_create_mi(self) -> None:
        """Test case for create_mi

        Create a new MI record
        """
        pass

    def test_get_mi(self) -> None:
        """Test case for get_mi

        Fetch a specific MI record
        """
        pass

    def test_list_mi(self) -> None:
        """Test case for list_mi

        List MI records
        """
        pass


if __name__ == '__main__':
    unittest.main()
