# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.letter_data import LetterData

class TestLetterData(unittest.TestCase):
    """LetterData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LetterData:
        """Test LetterData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LetterData`
        """
        model = LetterData()
        if include_optional:
            return LetterData(
                type = None,
                id = '',
                attributes = openapi_client.models.letter_attributes.LetterAttributes(
                    download = openapi_client.models.download.Download(
                        link = '',
                        expiry = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                    letters = [
                        openapi_client.models.letter.Letter(
                            message_id = '',
                            file_name = '', )
                        ], )
            )
        else:
            return LetterData(
        )
        """

    def testLetterData(self):
        """Test LetterData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
