# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.letter_status_data import LetterStatusData

class TestLetterStatusData(unittest.TestCase):
    """LetterStatusData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LetterStatusData:
        """Test LetterStatusData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LetterStatusData`
        """
        model = LetterStatusData()
        if include_optional:
            return LetterStatusData(
                data = openapi_client.models.letter_status_data_data.LetterStatusData_data(
                    type = 'Letter',
                    id = '',
                    attributes = openapi_client.models.letter_status_data_data_attributes.LetterStatusData_data_attributes(
                        status = 'PENDING',
                        requested_production_status = 'ACTIVE',
                        reason_code = 1.337,
                        reason_text = '', ), )
            )
        else:
            return LetterStatusData(
        )
        """

    def testLetterStatusData(self):
        """Test LetterStatusData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
