# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.letter_update_data_data import LetterUpdateDataData

class TestLetterUpdateDataData(unittest.TestCase):
    """LetterUpdateDataData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LetterUpdateDataData:
        """Test LetterUpdateDataData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LetterUpdateDataData`
        """
        model = LetterUpdateDataData()
        if include_optional:
            return LetterUpdateDataData(
                type = None,
                id = '',
                attributes = openapi_client.models.letter_update_data_data_attributes.LetterUpdateData_data_attributes(
                    status = 'ACKNOWLEDGED',
                    reason_code = 1.337,
                    reason_text = '', )
            )
        else:
            return LetterUpdateDataData(
        )
        """

    def testLetterUpdateDataData(self):
        """Test LetterUpdateDataData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
