# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.whitemail_api import WhitemailApi


class TestWhitemailApi(unittest.TestCase):
    """WhitemailApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WhitemailApi()

    def tearDown(self) -> None:
        pass

    def test_create_whitemail(self) -> None:
        """Test case for create_whitemail

        Create a new whitemail letter batch
        """
        pass

    def test_get_whitemail(self) -> None:
        """Test case for get_whitemail

        Fetch metadata about a specific whitemail batch
        """
        pass

    def test_list_whitemail(self) -> None:
        """Test case for list_whitemail

        List batches of whitemail letters
        """
        pass


if __name__ == '__main__':
    unittest.main()
