# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.return_api import ReturnApi


class TestReturnApi(unittest.TestCase):
    """ReturnApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReturnApi()

    def tearDown(self) -> None:
        pass

    def test_create_return(self) -> None:
        """Test case for create_return

        Create a new returned letter batch
        """
        pass

    def test_get_return(self) -> None:
        """Test case for get_return

        Fetch metadata about a specific return batch
        """
        pass

    def test_list_return(self) -> None:
        """Test case for list_return

        List batches of returned letters
        """
        pass


if __name__ == '__main__':
    unittest.main()
