# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.letter_update_data_data_attributes import LetterUpdateDataDataAttributes

class TestLetterUpdateDataDataAttributes(unittest.TestCase):
    """LetterUpdateDataDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LetterUpdateDataDataAttributes:
        """Test LetterUpdateDataDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LetterUpdateDataDataAttributes`
        """
        model = LetterUpdateDataDataAttributes()
        if include_optional:
            return LetterUpdateDataDataAttributes(
                status = 'ACKNOWLEDGED',
                reason_code = 1.337,
                reason_text = ''
            )
        else:
            return LetterUpdateDataDataAttributes(
        )
        """

    def testLetterUpdateDataDataAttributes(self):
        """Test LetterUpdateDataDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
