# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.batch_response_data import BatchResponseData

class TestBatchResponseData(unittest.TestCase):
    """BatchResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchResponseData:
        """Test BatchResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchResponseData`
        """
        model = BatchResponseData()
        if include_optional:
            return BatchResponseData(
                type = None,
                id = '',
                attributes = openapi_client.models.batch_response_data_attributes.BatchResponse_data_attributes(
                    download = openapi_client.models.download.Download(
                        expiry = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        url = '', ), 
                    letters = [
                        openapi_client.models.letter.Letter(
                            message_id = '', 
                            file_name = '', )
                        ], )
            )
        else:
            return BatchResponseData(
                type = None,
                id = '',
                attributes = openapi_client.models.batch_response_data_attributes.BatchResponse_data_attributes(
                    download = openapi_client.models.download.Download(
                        expiry = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        url = '', ), 
                    letters = [
                        openapi_client.models.letter.Letter(
                            message_id = '', 
                            file_name = '', )
                        ], ),
        )
        """

    def testBatchResponseData(self):
        """Test BatchResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
