# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.letter_api import LetterApi


class TestLetterApi(unittest.TestCase):
    """LetterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LetterApi()

    def tearDown(self) -> None:
        pass

    def test_get_a_list_of_letters(self) -> None:
        """Test case for get_a_list_of_letters

        Get a list of letters
        """
        pass

    def test_get_letter_status(self) -> None:
        """Test case for get_letter_status

        Retrieve the status of a letter
        """
        pass

    def test_patch_letters(self) -> None:
        """Test case for patch_letters

        Update the status of a letter
        """
        pass

    def test_post_letter(self) -> None:
        """Test case for post_letter

        Update the status of multiple letters
        """
        pass


if __name__ == '__main__':
    unittest.main()
