# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.batch_status import BatchStatus

class TestBatchStatus(unittest.TestCase):
    """BatchStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchStatus(self):
        """Test BatchStatus"""
        # inst = BatchStatus()

if __name__ == '__main__':
    unittest.main()
