# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.data_api import DataApi


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataApi()

    def tearDown(self) -> None:
        pass

    def test_get_data_id(self) -> None:
        """Test case for get_data_id

        Fetch a data file
        """
        pass

    def test_head_data_id(self) -> None:
        """Test case for head_data_id

        Fetch data file metadata
        """
        pass

    def test_post_data(self) -> None:
        """Test case for post_data

        Request a URL to upload a new data file
        """
        pass


if __name__ == '__main__':
    unittest.main()
