# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.artwork_api import ArtworkApi


class TestArtworkApi(unittest.TestCase):
    """ArtworkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArtworkApi()

    def tearDown(self) -> None:
        pass

    def test_create_artwork(self) -> None:
        """Test case for create_artwork

        Create a new artwork metadata record
        """
        pass

    def test_get_artwork(self) -> None:
        """Test case for get_artwork

        Fetch metadata about a specific artwork file
        """
        pass

    def test_list_artwork(self) -> None:
        """Test case for list_artwork

        List artwork files
        """
        pass

    def test_patch_artwork(self) -> None:
        """Test case for patch_artwork

        Update metadata about a specific artwork file
        """
        pass


if __name__ == '__main__':
    unittest.main()
