# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_cancellation_get(self) -> None:
        """Test case for cancellation_get

        Get a list of cancelled letters
        """
        pass

    def test_create_artwork(self) -> None:
        """Test case for create_artwork

        Create a new artwork metadata record
        """
        pass

    def test_create_mi(self) -> None:
        """Test case for create_mi

        Create a new MI record
        """
        pass

    def test_create_proof(self) -> None:
        """Test case for create_proof

        Create a new proof metadata record
        """
        pass

    def test_create_return(self) -> None:
        """Test case for create_return

        Create a new returned letter batch
        """
        pass

    def test_create_specification(self) -> None:
        """Test case for create_specification

        Create a new specification record
        """
        pass

    def test_get_artwork(self) -> None:
        """Test case for get_artwork

        Fetch metadata about a specific artwork file
        """
        pass

    def test_get_batch_id(self) -> None:
        """Test case for get_batch_id

        Retrieve a batch of letters
        """
        pass

    def test_get_batches(self) -> None:
        """Test case for get_batches

        Retrieve a list of available letter batches
        """
        pass

    def test_get_data(self) -> None:
        """Test case for get_data

        Fetch metadata about an existing data file
        """
        pass

    def test_get_letter_status(self) -> None:
        """Test case for get_letter_status

        Retrieve the status of a letter
        """
        pass

    def test_get_mi(self) -> None:
        """Test case for get_mi

        Fetch a specific MI record
        """
        pass

    def test_get_proof(self) -> None:
        """Test case for get_proof

        Fetch metadata about a specific proof file
        """
        pass

    def test_get_return(self) -> None:
        """Test case for get_return

        Fetch metadata about a specific return batch
        """
        pass

    def test_get_specification(self) -> None:
        """Test case for get_specification

        Fetch metadata about a specific specification
        """
        pass

    def test_letter_post(self) -> None:
        """Test case for letter_post

        Update the status of multiple letters
        """
        pass

    def test_list_artwork(self) -> None:
        """Test case for list_artwork

        List artwork files
        """
        pass

    def test_list_mi(self) -> None:
        """Test case for list_mi

        List MI records
        """
        pass

    def test_list_proof(self) -> None:
        """Test case for list_proof

        List proof files
        """
        pass

    def test_list_return(self) -> None:
        """Test case for list_return

        List batches of returned letters
        """
        pass

    def test_list_specification(self) -> None:
        """Test case for list_specification

        List specifications
        """
        pass

    def test_patch_artwork(self) -> None:
        """Test case for patch_artwork

        Update metadata about a specific artwork file
        """
        pass

    def test_patch_letters(self) -> None:
        """Test case for patch_letters

        Update the status of a letter
        """
        pass

    def test_patch_letters_batch(self) -> None:
        """Test case for patch_letters_batch

        Update the status of a batch of letters
        """
        pass

    def test_patch_proof(self) -> None:
        """Test case for patch_proof

        Update metadata about a specific proof file
        """
        pass

    def test_patch_specification(self) -> None:
        """Test case for patch_specification

        Update metadata about a specific specification
        """
        pass

    def test_post_data(self) -> None:
        """Test case for post_data

        Request a URL to upload a new data file
        """
        pass


if __name__ == '__main__':
    unittest.main()
