# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_batches200_response_data_inner import GetBatches200ResponseDataInner

class TestGetBatches200ResponseDataInner(unittest.TestCase):
    """GetBatches200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBatches200ResponseDataInner:
        """Test GetBatches200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBatches200ResponseDataInner`
        """
        model = GetBatches200ResponseDataInner()
        if include_optional:
            return GetBatches200ResponseDataInner(
                type = 'Batch',
                id = ''
            )
        else:
            return GetBatches200ResponseDataInner(
                type = 'Batch',
                id = '',
        )
        """

    def testGetBatches200ResponseDataInner(self):
        """Test GetBatches200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
