version: 2

updates:

  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/sandbox"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "pip"
    directory: "**/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "terraform"
    directories:
      - "/infrastructure/terraform/**/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
