name: "Build libraries"
description: "build libraries"
inputs:
  version:
    description: "Version number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://npm.pkg.github.com'

    - name: Npm install
      working-directory: .
      run: npm ci
      shell: bash

    - name: Build servers
      working-directory: ./src/server
      shell: bash
      run: |
        make build VERSION="${{ inputs.version }}"

    - name: Upload abstractions artifact
      uses: actions/upload-artifact@v4
      with:
        path: "src/server/abstractions/bin/Release"
        name: libs-abstractions-${{ inputs.version }}
        include-hidden-files: true

    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        path: "src/server/data/bin/Release"
        name: libs-data-${{ inputs.version }}
        include-hidden-files: true

    - name: Upload letter artifact
      uses: actions/upload-artifact@v4
      with:
        path: "src/server/letter/bin/Release"
        name: libs-letter-${{ inputs.version }}
        include-hidden-files: true

    - name: Upload host artifact
      uses: actions/upload-artifact@v4
      with:
        path: "src/server/host/bin/Release"
        name: libs-host-${{ inputs.version }}
        include-hidden-files: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - run: mkdir -p ${{ runner.temp }}/myimage
      shell: bash

    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        context: src/server
        file: src/server/Dockerfile
        tags: |
          ghcr.io/nhsdigital/libshostdocker:latest
#          ghcr.io/nhsdigital/libshostdocker:${{ inputs.version }}
        outputs: type=docker,dest=${{ runner.temp }}/myimage/myimage.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: libs-host-docker-${{ inputs.version }}
        path: ${{ runner.temp }}/myimage
