# coding: utf-8

# flake8: noqa

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "BatchApi",
    "DataApi",
    "LetterApi",
    "MiApi",
    "WhitemailApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Batch",
    "BatchResponse",
    "BatchResponseData",
    "BatchStatus",
    "BatchUpdateData",
    "BatchUpdateDataData",
    "BatchUpdateDataDataAttributes",
    "DataReference",
    "ErrorData",
    "ErrorItem",
    "ErrorItemLinks",
    "ErrorResponse",
    "GetBatches200Response",
    "GetBatches200ResponseDataInner",
    "GetBatches200ResponseLinks",
    "Letter",
    "LetterStatus",
    "LetterStatusData",
    "LetterStatusDataData",
    "LetterStatusDataDataAttributes",
    "LetterUpdateData",
    "LetterUpdateDataData",
    "LetterUpdateDataDataAttributes",
    "ProductionStatus",
]

# import apis into sdk package
from openapi_client.api.batch_api import BatchApi as BatchApi
from openapi_client.api.data_api import DataApi as DataApi
from openapi_client.api.letter_api import LetterApi as LetterApi
from openapi_client.api.mi_api import MiApi as MiApi
from openapi_client.api.whitemail_api import WhitemailApi as WhitemailApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.batch import Batch as Batch
from openapi_client.models.batch_response import BatchResponse as BatchResponse
from openapi_client.models.batch_response_data import BatchResponseData as BatchResponseData
from openapi_client.models.batch_status import BatchStatus as BatchStatus
from openapi_client.models.batch_update_data import BatchUpdateData as BatchUpdateData
from openapi_client.models.batch_update_data_data import BatchUpdateDataData as BatchUpdateDataData
from openapi_client.models.batch_update_data_data_attributes import BatchUpdateDataDataAttributes as BatchUpdateDataDataAttributes
from openapi_client.models.data_reference import DataReference as DataReference
from openapi_client.models.error_data import ErrorData as ErrorData
from openapi_client.models.error_item import ErrorItem as ErrorItem
from openapi_client.models.error_item_links import ErrorItemLinks as ErrorItemLinks
from openapi_client.models.error_response import ErrorResponse as ErrorResponse
from openapi_client.models.get_batches200_response import GetBatches200Response as GetBatches200Response
from openapi_client.models.get_batches200_response_data_inner import GetBatches200ResponseDataInner as GetBatches200ResponseDataInner
from openapi_client.models.get_batches200_response_links import GetBatches200ResponseLinks as GetBatches200ResponseLinks
from openapi_client.models.letter import Letter as Letter
from openapi_client.models.letter_status import LetterStatus as LetterStatus
from openapi_client.models.letter_status_data import LetterStatusData as LetterStatusData
from openapi_client.models.letter_status_data_data import LetterStatusDataData as LetterStatusDataData
from openapi_client.models.letter_status_data_data_attributes import LetterStatusDataDataAttributes as LetterStatusDataDataAttributes
from openapi_client.models.letter_update_data import LetterUpdateData as LetterUpdateData
from openapi_client.models.letter_update_data_data import LetterUpdateDataData as LetterUpdateDataData
from openapi_client.models.letter_update_data_data_attributes import LetterUpdateDataDataAttributes as LetterUpdateDataDataAttributes
from openapi_client.models.production_status import ProductionStatus as ProductionStatus
