# coding: utf-8

# flake8: noqa

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.batch_api import BatchApi
from openapi_client.api.data_api import DataApi
from openapi_client.api.letter_api import LetterApi
from openapi_client.api.mi_api import MiApi
from openapi_client.api.whitemail_api import WhitemailApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.batch import Batch
from openapi_client.models.batch_response import BatchResponse
from openapi_client.models.batch_response_data import BatchResponseData
from openapi_client.models.batch_status import BatchStatus
from openapi_client.models.batch_update_data import BatchUpdateData
from openapi_client.models.batch_update_data_data import BatchUpdateDataData
from openapi_client.models.batch_update_data_data_attributes import BatchUpdateDataDataAttributes
from openapi_client.models.data_reference import DataReference
from openapi_client.models.error_data import ErrorData
from openapi_client.models.error_item import ErrorItem
from openapi_client.models.error_item_links import ErrorItemLinks
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.get_batches200_response import GetBatches200Response
from openapi_client.models.get_batches200_response_data_inner import GetBatches200ResponseDataInner
from openapi_client.models.get_batches200_response_links import GetBatches200ResponseLinks
from openapi_client.models.letter import Letter
from openapi_client.models.letter_status import LetterStatus
from openapi_client.models.letter_status_data import LetterStatusData
from openapi_client.models.letter_status_data_data import LetterStatusDataData
from openapi_client.models.letter_status_data_data_attributes import LetterStatusDataDataAttributes
from openapi_client.models.letter_update_data import LetterUpdateData
from openapi_client.models.letter_update_data_data import LetterUpdateDataData
from openapi_client.models.letter_update_data_data_attributes import LetterUpdateDataDataAttributes
from openapi_client.models.production_status import ProductionStatus
