name: 'npm install and setup'
description: 'Setup node, authenticate github package repository and perform clean npm install'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
  GITHUB_TOKEN:
    description: "Token for access to github package registry"
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Use Node.js'
      uses: actions/setup-node@v6
      with:
        node-version: '${{ inputs.node-version }}'

    - name: 'Install dependencies'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        scripts/set-github-token.sh
        npm ci
