/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 * OpenAPI spec version: 0.0.1
 */

/**
 * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
The ID will be returned in a response header.
 */
export type CorrelationIdParameter = string;
