/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 * OpenAPI spec version: 0.0.1
 */

export type ErrorItemCode = typeof ErrorItemCode[keyof typeof ErrorItemCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorItemCode = {
  CM_NO_BATCH_AVAILABLE: 'CM_NO_BATCH_AVAILABLE',
  CM_INTERNAL_SERVER_ERROR: 'CM_INTERNAL_SERVER_ERROR',
  CM_INVALID_REQUEST: 'CM_INVALID_REQUEST',
  CM_LETTER_NOT_FOUND: 'CM_LETTER_NOT_FOUND',
} as const;
