/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 * OpenAPI spec version: 0.0.1
 */

/**
 * New status to be applied to the letter
 */
export type LetterUpdateDataDataAttributesStatus = typeof LetterUpdateDataDataAttributesStatus[keyof typeof LetterUpdateDataDataAttributesStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LetterUpdateDataDataAttributesStatus = {
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  PENDING: 'PENDING',
  HOLD: 'HOLD',
  CANCELLED: 'CANCELLED',
  PROCESSING: 'PROCESSING',
  PRINTED: 'PRINTED',
  FAILED: 'FAILED',
  DISPATCHED: 'DISPATCHED',
} as const;
