/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 * OpenAPI spec version: 0.0.1
 */
import type { LetterBatchUpdateDataDataAttributesStatus } from './letterBatchUpdateDataDataAttributesStatus';

export type LetterBatchUpdateDataDataAttributes = {
  /** New status to be applied to the batch of letters */
  status?: LetterBatchUpdateDataDataAttributesStatus;
  /** Reason code for the given status */
  reasonCode?: number;
  /** Reason code for the given status */
  reasonText?: string;
};
