/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 * OpenAPI spec version: 0.0.1
 */
import type { LetterUpdateDataDataAttributesStatus } from './letterUpdateDataDataAttributesStatus';

export type LetterUpdateDataDataAttributes = {
  /** New status to be applied to the letter */
  status?: LetterUpdateDataDataAttributesStatus;
  /** Reason code for the given status */
  reasonCode?: number;
  /** Reason code for the given status */
  reasonText?: string;
};
