/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 * OpenAPI spec version: 0.0.1
 */

/**
 * Unique request identifier, in the format of a GUID
 */
export type RequestIdParameter = string;
