/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BatchUpdateDataDataAttributes } from '../models/BatchUpdateDataDataAttributes';
import { HttpFile } from '../http/http';

export class BatchUpdateDataData {
    'type'?: any | null;
    'id'?: string;
    'attributes'?: BatchUpdateDataDataAttributes;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "any",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "BatchUpdateDataDataAttributes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchUpdateDataData.attributeTypeMap;
    }

    public constructor() {
    }
}
