/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BatchUpdateDataData } from '../models/BatchUpdateDataData';
import { HttpFile } from '../http/http';

export class BatchUpdateData {
    'data'?: BatchUpdateDataData;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "BatchUpdateDataData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchUpdateData.attributeTypeMap;
    }

    public constructor() {
    }
}
