/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BatchStatus } from '../models/BatchStatus';
import { DataReference } from '../models/DataReference';
import { Letter } from '../models/Letter';
import { HttpFile } from '../http/http';

export class Batch {
    'status': BatchStatus;
    'data'?: DataReference;
    'letters': Array<Letter>;
    'reasonCode'?: number;
    'reasonText'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchStatus",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "DataReference",
            "format": ""
        },
        {
            "name": "letters",
            "baseName": "letters",
            "type": "Array<Letter>",
            "format": ""
        },
        {
            "name": "reasonCode",
            "baseName": "reasonCode",
            "type": "number",
            "format": ""
        },
        {
            "name": "reasonText",
            "baseName": "reasonText",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Batch.attributeTypeMap;
    }

    public constructor() {
    }
}
