/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorItemLinks } from '../models/ErrorItemLinks';
import { HttpFile } from '../http/http';

export class ErrorItem {
    'id'?: string;
    'code'?: ErrorItemCodeEnum;
    'links'?: ErrorItemLinks;
    'status'?: string;
    'title'?: string;
    'detail'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "ErrorItemCodeEnum",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ErrorItemLinks",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorItem.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ErrorItemCodeEnum {
    NotifyNoBatchAvailable = 'NOTIFY_NO_BATCH_AVAILABLE',
    NotifyInternalServerError = 'NOTIFY_INTERNAL_SERVER_ERROR',
    NotifyInvalidRequest = 'NOTIFY_INVALID_REQUEST',
    NotifyLetterNotFound = 'NOTIFY_LETTER_NOT_FOUND'
}

