/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorItem } from '../models/ErrorItem';
import { HttpFile } from '../http/http';

export class ErrorData {
    'errors'?: Array<ErrorItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ErrorItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorData.attributeTypeMap;
    }

    public constructor() {
    }
}
