/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ErrorItemLinks {
    'about'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "about",
            "baseName": "about",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return ErrorItemLinks.attributeTypeMap;
    }

    public constructor() {
    }
}
