/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetBatches200ResponseLinks {
    'self': string;
    'first': string;
    'last': string;
    'prev'?: string;
    'next'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "string",
            "format": ""
        },
        {
            "name": "first",
            "baseName": "first",
            "type": "string",
            "format": ""
        },
        {
            "name": "last",
            "baseName": "last",
            "type": "string",
            "format": ""
        },
        {
            "name": "prev",
            "baseName": "prev",
            "type": "string",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetBatches200ResponseLinks.attributeTypeMap;
    }

    public constructor() {
    }
}
