/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetBatches200ResponseDataInner {
    'type': GetBatches200ResponseDataInnerTypeEnum;
    /**
    * ID of a batch which can be fetched from the /batch/{id} endpoint
    */
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GetBatches200ResponseDataInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetBatches200ResponseDataInner.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GetBatches200ResponseDataInnerTypeEnum {
    Batch = 'Batch'
}

