/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetBatches200ResponseDataInner } from '../models/GetBatches200ResponseDataInner';
import { GetBatches200ResponseLinks } from '../models/GetBatches200ResponseLinks';
import { HttpFile } from '../http/http';

export class GetBatches200Response {
    'links'?: GetBatches200ResponseLinks;
    'data'?: Array<GetBatches200ResponseDataInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "links",
            "baseName": "links",
            "type": "GetBatches200ResponseLinks",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<GetBatches200ResponseDataInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetBatches200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
