/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Letter {
    'messageId': string;
    'fileName': string;
    /**
    * SHA 256 Hash of a file or other resource used to verify the expected content
    */
    'sha256': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageId",
            "baseName": "messageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha256",
            "baseName": "sha256",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Letter.attributeTypeMap;
    }

    public constructor() {
    }
}
