/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LetterStatus } from '../models/LetterStatus';
import { ProductionStatus } from '../models/ProductionStatus';
import { HttpFile } from '../http/http';

export class LetterStatusDataDataAttributes {
    'status': LetterStatus;
    'requestedProductionStatus': ProductionStatus;
    /**
    * Reason code for the given status
    */
    'reasonCode'?: number;
    /**
    * Reason text for the given status
    */
    'reasonText'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "LetterStatus",
            "format": ""
        },
        {
            "name": "requestedProductionStatus",
            "baseName": "requestedProductionStatus",
            "type": "ProductionStatus",
            "format": ""
        },
        {
            "name": "reasonCode",
            "baseName": "reasonCode",
            "type": "number",
            "format": ""
        },
        {
            "name": "reasonText",
            "baseName": "reasonText",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LetterStatusDataDataAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}
