/**
 * NHS Notify Supplier API
 * API for communication suppliers to integrate with NHS Notify
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The supplier status of an individual letter
*/
export enum LetterStatus {
    Pending = 'PENDING',
    Accepted = 'ACCEPTED',
    Rejected = 'REJECTED',
    Printed = 'PRINTED',
    Enclosed = 'ENCLOSED',
    Cancelled = 'CANCELLED',
    Dispatched = 'DISPATCHED',
    Failed = 'FAILED',
    Returned = 'RETURNED',
    Destroyed = 'DESTROYED',
    Forwarded = 'FORWARDED'
}
