name: Acceptance tests
description: "Run acceptance tests for this repo"

inputs:
  testType:
    description: Type of test to run
    required: true

  targetEnvironment:
    description: Name of the environment under test
    required: true

  targetAccountGroup:
    description: Name of the account group under test
    default: nhs-notify-template-management-dev
    required: true

  targetComponent:
    description: Name of the component under test
    required: true

runs:
  using: "composite"

  steps:
    - name: Fetch terraform output
      uses: actions/download-artifact@v5
      with:
        name: terraform-output-${{ inputs.targetComponent }}

    - name: Get Node version
      id: nodejs_version
      shell: bash
      run: |
        echo "nodejs_version=$(grep "^nodejs\s" .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT

    - name: "Repo setup"
      uses: ./.github/actions/node-install
      with:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: "Set PR NUMBER"
      shell: bash
      run: |
          echo "PR_NUMBER=${{ inputs.targetEnvironment }}" >> $GITHUB_ENV

    - name: Run component tests
      shell: bash
      run: |
        make test-component

    - name: Check if e2e tests should run
      id: check_e2e
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        # Extract PR number from environment name (e.g., pr123 -> 123)
        if [[ "${{ inputs.targetEnvironment }}" =~ ^pr([0-9]+)$ ]]; then
          pr_number="${BASH_REMATCH[1]}"
          labels=$(gh pr view "$pr_number" --json labels --jq '.labels[].name' 2>/dev/null || echo "")

          if echo "$labels" | grep -Fxq 'deploy-proxy'; then
            echo "deploy-proxy label found; e2e tests will run."
            echo "run_e2e=true" >> $GITHUB_OUTPUT
          else
            echo "deploy-proxy label not found; e2e tests will be skipped."
            echo "run_e2e=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "Not a PR environment; e2e tests will run."
          echo "run_e2e=true" >> $GITHUB_OUTPUT
        fi

    - name: Run e2e tests
      if: steps.check_e2e.outputs.run_e2e == 'true'
      shell: bash
      run: |
        make .internal-dev-test
