name: Acceptance tests
description: "Run acceptance tests for this repo"

inputs:
  testType:
    description: Type of test to run
    required: true

  targetEnvironment:
    description: Name of the environment under test
    required: true

  targetAccountGroup:
    description: Name of the account group under test
    default: nhs-notify-template-management-dev
    required: true

  targetComponent:
    description: Name of the component under test
    required: true

runs:
  using: "composite"

  steps:

    - name: Run component tests
      if: ${{ inputs.testType != 'e2e' }}
      uses: ./.github/actions/acceptance-tests-component
      with:
        testType: ${{ inputs.testType }}
        targetEnvironment: ${{ inputs.targetEnvironment }}
        targetComponent: ${{ inputs.targetComponent }}

    - name: Run e2e tests
      if: ${{ inputs.testType == 'e2e' && inputs.targetEnvironment == 'main' }}
      uses: ./.github/actions/acceptance-tests-e2e
      with:
        targetEnvironment: ${{ inputs.targetEnvironment }}
