// This file is auto-generated by @hey-api/openapi-ts

export type Download = {
    expiry: string;
    url: string;
};

export type Letter = {
    messageId?: string;
    fileName?: string;
};

export type ErrorResponse = {
    data?: ErrorData;
};

export type ErrorData = {
    errors?: Array<ErrorItem>;
};

export type ErrorItem = {
    id?: string;
    code?: 'CM_NO_BATCH_AVAILABLE' | 'CM_INTERNAL_SERVER_ERROR' | 'CM_INVALID_REQUEST' | 'CM_LETTER_NOT_FOUND';
    links?: {
        about?: string;
    };
    status?: string;
    title?: string;
    detail?: string;
};

export type LetterBatchUpdateRequest = LetterBatchUpdateData;

export type LetterBatchUpdateData = {
    data?: {
        type?: 'Letter';
        id?: string;
        attributes?: {
            /**
             * New status to be applied to the batch of letters
             */
            status?: LetterStatus;
            /**
             * Reason code for the given status
             */
            reasonCode?: number;
            /**
             * Reason text for the given status
             */
            reasonText?: string;
        };
    };
};

export type LetterBatchUpdateResponse = LetterBatchUpdateData;

export type LetterUpdateRequest = LetterUpdateData;

export type LetterUpdateData = {
    data?: {
        type?: 'Letter';
        id?: string;
        attributes?: {
            status?: LetterStatus;
            /**
             * Reason code for the given status
             */
            reasonCode?: number;
            /**
             * Reason text for the given status
             */
            reasonText?: string;
        };
    };
};

export type LetterStatusResponse = LetterStatusData;

export type LetterStatusData = {
    data?: {
        type?: 'Letter';
        id?: string;
        attributes?: {
            status: LetterStatus;
            /**
             * Reason code for the given status
             */
            reasonCode?: number;
            /**
             * Reason text for the given status
             */
            reasonText?: string;
        };
    };
};

/**
 * The status of an individual letter
 */
export type LetterStatus = 'PENDING' | 'ACCEPTED' | 'REJECTED' | 'CANCELLED' | 'DISPATCHED' | 'FAILED' | 'RETURNED' | 'DESTROYED';

export type BatchResponse = {
    data: {
        type: 'Letters';
        id: string;
        attributes: {
            download: Download;
            letters: Array<Letter>;
        };
    };
};

/**
 * Unique request identifier, in the format of a GUID
 */
export type RequestId = string;

/**
 * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
 * The ID will be returned in a response header.
 */
export type CorrelationId = string;

/**
 * Unique identifier of this resource
 */
export type Id = string;

/**
 * Status of a letter
 */
export type Status = LetterStatus;

export type GetBatchesData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/batch';
};

export type GetBatchIdData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/batch/{id}';
};

export type GetBatchIdErrors = {
    /**
     * No batch of letters available
     */
    404: ErrorResponse;
    /**
     * Too many requests
     */
    429: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type GetBatchIdError = GetBatchIdErrors[keyof GetBatchIdErrors];

export type GetBatchIdResponses = {
    /**
     * Batch of letters found
     */
    200: BatchResponse;
};

export type GetBatchIdResponse = GetBatchIdResponses[keyof GetBatchIdResponses];

export type PatchLettersBatchData = {
    body: LetterBatchUpdateData;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/batch/{id}';
};

export type PatchLettersBatchErrors = {
    /**
     * Bad request, invalid input data
     */
    400: ErrorResponse;
    /**
     * Letter resource not found
     */
    404: ErrorResponse;
    /**
     * Too many requests
     */
    429: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type PatchLettersBatchError = PatchLettersBatchErrors[keyof PatchLettersBatchErrors];

export type PatchLettersBatchResponses = {
    /**
     * Letters resources updated successfully
     */
    200: LetterBatchUpdateData;
};

export type PatchLettersBatchResponse = PatchLettersBatchResponses[keyof PatchLettersBatchResponses];

export type GetAListOfLettersData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query: {
        /**
         * Status of a letter
         */
        status: LetterStatus;
    };
    url: '/letter';
};

export type PostLetterData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/letter';
};

export type GetLetterStatusData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/letter/{id}';
};

export type GetLetterStatusErrors = {
    /**
     * Could not find letter
     */
    404: ErrorResponse;
    /**
     * Too many requests
     */
    429: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type GetLetterStatusError = GetLetterStatusErrors[keyof GetLetterStatusErrors];

export type GetLetterStatusResponses = {
    /**
     * Letter status
     */
    200: LetterStatusData;
};

export type GetLetterStatusResponse = GetLetterStatusResponses[keyof GetLetterStatusResponses];

export type PatchLettersData = {
    body: LetterUpdateData;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/letter/{id}';
};

export type PatchLettersErrors = {
    /**
     * Bad request, invalid input data
     */
    400: ErrorResponse;
    /**
     * Letter resource not found
     */
    404: ErrorResponse;
    /**
     * Too many requests
     */
    429: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type PatchLettersError = PatchLettersErrors[keyof PatchLettersErrors];

export type PatchLettersResponses = {
    /**
     * Letter resource updated successfully
     */
    200: LetterStatusData;
};

export type PatchLettersResponse = PatchLettersResponses[keyof PatchLettersResponses];

export type ListMiData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/mi';
};

export type CreateMiData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/mi';
};

export type GetMiData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/mi/{id}';
};

export type ListSpecificationData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/specification';
};

export type CreateSpecificationData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/specification';
};

export type GetSpecificationData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/specification/{id}';
};

export type PatchSpecificationData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/specification/{id}';
};

export type ListProofData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/proof';
};

export type CreateProofData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/proof';
};

export type GetProofData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/proof/{id}';
};

export type PatchProofData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/proof/{id}';
};

export type ListArtworkData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/artwork';
};

export type CreateArtworkData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/artwork';
};

export type GetArtworkData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/artwork/{id}';
};

export type PatchArtworkData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/artwork/{id}';
};

export type ListReturnData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/return';
};

export type CreateReturnData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/return';
};

export type GetReturnData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/return/{id}';
};

export type PostDataData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/data';
};

export type GetDataData = {
    body?: never;
    headers: {
        /**
         * Unique request identifier, in the format of a GUID
         */
        'X-Request-ID': string;
        /**
         * An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         * The ID will be returned in a response header.
         */
        'X-Correlation-ID'?: string;
    };
    path: {
        /**
         * Unique identifier of this resource
         */
        id: string;
    };
    query?: never;
    url: '/data/{id}';
};

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:3000' | 'https://sandbox-server.nhs.uk/nhs-notify-supplier-api' | (string & {});
};