# coding: utf-8

# flake8: noqa
"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.batch import Batch
from openapi_client.models.batch_response import BatchResponse
from openapi_client.models.batch_response_data import BatchResponseData
from openapi_client.models.batch_status import BatchStatus
from openapi_client.models.batch_update_data import BatchUpdateData
from openapi_client.models.batch_update_data_data import BatchUpdateDataData
from openapi_client.models.batch_update_data_data_attributes import BatchUpdateDataDataAttributes
from openapi_client.models.data_reference import DataReference
from openapi_client.models.error_data import ErrorData
from openapi_client.models.error_item import ErrorItem
from openapi_client.models.error_item_links import ErrorItemLinks
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.get_batches200_response import GetBatches200Response
from openapi_client.models.get_batches200_response_data_inner import GetBatches200ResponseDataInner
from openapi_client.models.get_batches200_response_links import GetBatches200ResponseLinks
from openapi_client.models.letter import Letter
from openapi_client.models.letter_status import LetterStatus
from openapi_client.models.letter_status_data import LetterStatusData
from openapi_client.models.letter_status_data_data import LetterStatusDataData
from openapi_client.models.letter_status_data_data_attributes import LetterStatusDataDataAttributes
from openapi_client.models.letter_update_data import LetterUpdateData
from openapi_client.models.letter_update_data_data import LetterUpdateDataData
from openapi_client.models.letter_update_data_data_attributes import LetterUpdateDataDataAttributes
from openapi_client.models.production_status import ProductionStatus
