# coding: utf-8

# flake8: noqa
"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.download import Download
from openapi_client.models.error_data import ErrorData
from openapi_client.models.error_item import ErrorItem
from openapi_client.models.error_item_links import ErrorItemLinks
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.letter import Letter
from openapi_client.models.letter_attributes import LetterAttributes
from openapi_client.models.letter_batch_update_data import LetterBatchUpdateData
from openapi_client.models.letter_batch_update_data_data import LetterBatchUpdateDataData
from openapi_client.models.letter_batch_update_data_data_attributes import LetterBatchUpdateDataDataAttributes
from openapi_client.models.letter_data import LetterData
from openapi_client.models.letter_statu_data import LetterStatuData
from openapi_client.models.letter_statu_data_data import LetterStatuDataData
from openapi_client.models.letter_statu_data_data_attributes import LetterStatuDataDataAttributes
from openapi_client.models.letter_update_data import LetterUpdateData
from openapi_client.models.letter_update_data_data import LetterUpdateDataData
from openapi_client.models.letter_update_data_data_attributes import LetterUpdateDataDataAttributes
from openapi_client.models.letters_response import LettersResponse
