# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BatchStatus(str, Enum):
    """
    The supplier status of a batch of letters
    """

    """
    allowed enum values
    """
    PENDING = 'PENDING'
    ACCEPTED = 'ACCEPTED'
    REJECTED = 'REJECTED'
    CANCELLED = 'CANCELLED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BatchStatus from a JSON string"""
        return cls(json.loads(json_str))


