# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.error_item_links import ErrorItemLinks
from typing import Optional, Set
from typing_extensions import Self

class ErrorItem(BaseModel):
    """
    ErrorItem
    """ # noqa: E501
    id: Optional[StrictStr] = None
    code: Optional[StrictStr] = None
    links: Optional[ErrorItemLinks] = None
    status: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    detail: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "code", "links", "status", "title", "detail"]

    @field_validator('code')
    def code_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NOTIFY_NO_BATCH_AVAILABLE', 'NOTIFY_INTERNAL_SERVER_ERROR', 'NOTIFY_INVALID_REQUEST', 'NOTIFY_LETTER_NOT_FOUND']):
            raise ValueError("must be one of enum values ('NOTIFY_NO_BATCH_AVAILABLE', 'NOTIFY_INTERNAL_SERVER_ERROR', 'NOTIFY_INVALID_REQUEST', 'NOTIFY_LETTER_NOT_FOUND')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ErrorItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ErrorItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "links": ErrorItemLinks.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "status": obj.get("status"),
            "title": obj.get("title"),
            "detail": obj.get("detail")
        })
        return _obj
