# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LetterStatus(str, Enum):
    """
    The status of an individual letter
    """

    """
    allowed enum values
    """
    PENDING = 'PENDING'
    ACCEPTED = 'ACCEPTED'
    REJECTED = 'REJECTED'
    CANCELLED = 'CANCELLED'
    DISPATCHED = 'DISPATCHED'
    FAILED = 'FAILED'
    RETURNED = 'RETURNED'
    DESTROYED = 'DESTROYED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LetterStatus from a JSON string"""
        return cls(json.loads(json_str))


