# coding: utf-8

"""
    NHS Notify Supplier API

    API for communication suppliers to integrate with NHS Notify

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProductionStatus(str, Enum):
    """
    A requested status for the production of a letter
    """

    """
    allowed enum values
    """
    ACTIVE = 'ACTIVE'
    HOLD = 'HOLD'
    CANCEL = 'CANCEL'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProductionStatus from a JSON string"""
        return cls(json.loads(json_str))
