name: "Build SDKs"
description: "build sdks"
inputs:
  version:
    description: "Version number"
    required: true
  NODE_AUTH_TOKEN:
    description: "Token for access to github package registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 22
        registry-url: 'https://npm.pkg.github.com'

    - name: Npm install
      working-directory: .
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
      run: npm ci
      shell: bash

    - name: make ts folder
      working-directory: ./sdk
      shell: bash
      run: mkdir typescript

    - name: make html folder
      working-directory: ./sdk
      shell: bash
      run: mkdir html

    - name: make python folder
      working-directory: ./sdk
      shell: bash
      run: mkdir python

    - name: make swagger folder
      working-directory: ./sdk
      shell: bash
      run: mkdir swagger

    - name: make csharp folder
      working-directory: ./sdk
      shell: bash
      run: mkdir csharp

    - name: Build sdks
      working-directory: ./sdk
      shell: bash
      run: |
        make build VERSION="${{ inputs.version }}"

    - name: Upload html artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: "sdk/html"
        name: sdk-html-${{ inputs.version }}

    - name: Upload swagger artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: "sdk/swagger"
        name: sdk-swagger-${{ inputs.version }}

    - name: Upload ts artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: "sdk/typescript"
        name: sdk-ts-${{ inputs.version }}

    - name: Upload python artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: "sdk/python"
        name: sdk-python-${{ inputs.version }}

    - name: Upload csharp artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: "sdk/csharp"
        name: sdk-csharp-${{ inputs.version }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        path: "sdk/html/"
        name: sdk-html-docs-${{ inputs.version }}

    - name: Upload swagger pages artifact
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        path: "sdk/swagger/"
        name: sdk-swagger-docs-${{ inputs.version }}
