/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/batch": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        /** Retrieve a list of available letter batches */
        get: operations["get-batches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batch/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /**
         * Retrieve a batch of letters
         * @description Get details about a batch of letters
         */
        get: operations["get-batch-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the status of a batch of letters
         * @description Update the status of a batch of letters by providing the new status in the request body.
         */
        patch: operations["patch-letters-batch"];
        trace?: never;
    };
    "/letter": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update the status of multiple letters */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique request identifier, in the format of a GUID */
                    "X-Request-ID": components["parameters"]["requestId"];
                    /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                     *     The ID will be returned in a response header. */
                    "X-Correlation-ID"?: components["parameters"]["correlationId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/letter/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /**
         * Retrieve the status of a letter
         * @description Get details the status of a letter.
         */
        get: operations["get-letter-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the status of a letter
         * @description Update the status of a letter by providing the new status in the request body.
         */
        patch: operations["patch-letters"];
        trace?: never;
    };
    "/cancellation": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        /** Get a list of cancelled letters */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique request identifier, in the format of a GUID */
                    "X-Request-ID": components["parameters"]["requestId"];
                    /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                     *     The ID will be returned in a response header. */
                    "X-Correlation-ID"?: components["parameters"]["correlationId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mi": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        /** List MI records */
        get: operations["list-mi"];
        put?: never;
        /** Create a new MI record */
        post: operations["create-mi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mi/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Fetch a specific MI record */
        get: operations["get-mi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specification": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        /** List specifications */
        get: operations["list-specification"];
        put?: never;
        /** Create a new specification record */
        post: operations["create-specification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specification/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Fetch metadata about a specific specification */
        get: operations["get-specification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update metadata about a specific specification */
        patch: operations["patch-specification"];
        trace?: never;
    };
    "/proof": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        /** List proof files */
        get: operations["list-proof"];
        put?: never;
        /** Create a new proof metadata record */
        post: operations["create-proof"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proof/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Fetch metadata about a specific proof file */
        get: operations["get-proof"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update metadata about a specific proof file */
        patch: operations["patch-proof"];
        trace?: never;
    };
    "/artwork": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        /** List artwork files */
        get: operations["list-artwork"];
        put?: never;
        /** Create a new artwork metadata record */
        post: operations["create-artwork"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artwork/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Fetch metadata about a specific artwork file */
        get: operations["get-artwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update metadata about a specific artwork file */
        patch: operations["patch-artwork"];
        trace?: never;
    };
    "/return": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        /** List batches of returned letters */
        get: operations["list-return"];
        put?: never;
        /** Create a new returned letter batch */
        post: operations["create-return"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/return/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Fetch metadata about a specific return batch */
        get: operations["get-return"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a URL to upload a new data file */
        post: operations["post-data"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Fetch metadata about an existing data file */
        get: operations["get-data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LettersResponse: {
            data?: components["schemas"]["LetterData"];
        };
        LetterData: {
            /** @constant */
            type?: "Letters";
            id?: string;
            attributes?: components["schemas"]["LetterAttributes"];
        };
        LetterAttributes: {
            download?: components["schemas"]["Download"];
            letters?: components["schemas"]["Letter"][];
        };
        Download: {
            /** Format: uri */
            link?: string;
            /** Format: date-time */
            expiry?: string;
        };
        Letter: {
            messageId?: string;
            fileName?: string;
        };
        ErrorResponse: {
            data?: components["schemas"]["ErrorData"];
        };
        ErrorData: {
            errors?: components["schemas"]["ErrorItem"][];
        };
        ErrorItem: {
            id?: string;
            /** @enum {string} */
            code?: "CM_NO_BATCH_AVAILABLE" | "CM_INTERNAL_SERVER_ERROR" | "CM_INVALID_REQUEST" | "CM_LETTER_NOT_FOUND";
            links?: {
                /** Format: uri */
                about?: string;
            };
            status?: string;
            title?: string;
            detail?: string;
        };
        LetterBatchUpdateRequest: components["schemas"]["LetterBatchUpdateData"];
        LetterBatchUpdateData: {
            data?: {
                /** @constant */
                type?: "Letter";
                id?: string;
                attributes?: {
                    /**
                     * @description New status to be applied to the batch of letters
                     * @enum {string}
                     */
                    status?: "ACKNOWLEDGED" | "PENDING" | "HOLD" | "CANCELLED" | "PROCESSING" | "PRINTED" | "FAILED" | "DISPATCHED";
                    /** @description Reason code for the given status */
                    reasonCode?: number;
                    /** @description Reason code for the given status */
                    reasonText?: string;
                };
            };
        };
        LetterBatchUpdateResponse: components["schemas"]["LetterBatchUpdateData"];
        LetterUpdateRequest: components["schemas"]["LetterUpdateData"];
        LetterUpdateData: {
            data?: {
                /** @constant */
                type?: "Letter";
                id?: string;
                attributes?: {
                    /**
                     * @description New status to be applied to the letter
                     * @enum {string}
                     */
                    status?: "ACKNOWLEDGED" | "PENDING" | "HOLD" | "CANCELLED" | "PROCESSING" | "PRINTED" | "FAILED" | "DISPATCHED";
                    /** @description Reason code for the given status */
                    reasonCode?: number;
                    /** @description Reason code for the given status */
                    reasonText?: string;
                };
            };
        };
        LetterUpdateResponse: components["schemas"]["LetterUpdateData"];
        LetterStatusResponse: components["schemas"]["LetterStatuData"];
        LetterStatuData: {
            data?: {
                /** @constant */
                type?: "Letter";
                id?: string;
                attributes?: {
                    /**
                     * @description New status to be applied to the letter
                     * @enum {string}
                     */
                    status?: "ACKNOWLEDGED" | "PENDING" | "HOLD" | "CANCELLED" | "PROCESSING" | "PRINTED" | "FAILED" | "DISPATCHED";
                };
            };
        };
    };
    responses: never;
    parameters: {
        /** @description Unique request identifier, in the format of a GUID */
        requestId: string;
        /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
         *     The ID will be returned in a response header. */
        correlationId: string;
        /** @description Unique identifier of this resource */
        id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-batches": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get-batch-id": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Batch of letters found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["LettersResponse"];
                };
            };
            /** @description No batch of letters available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "patch-letters-batch": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/vnd.api+json": components["schemas"]["LetterBatchUpdateRequest"];
            };
        };
        responses: {
            /** @description Letters resources updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["LetterBatchUpdateResponse"];
                };
            };
            /** @description Bad request, invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Letter resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "get-letter-status": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Letter status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["LetterStatusResponse"];
                };
            };
            /** @description Could not find letter */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "patch-letters": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/vnd.api+json": components["schemas"]["LetterUpdateRequest"];
            };
        };
        responses: {
            /** @description Letter resource updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["LetterUpdateResponse"];
                };
            };
            /** @description Bad request, invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Letter resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "list-mi": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "create-mi": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get-mi": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "list-specification": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "create-specification": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get-specification": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "patch-specification": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "list-proof": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "create-proof": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get-proof": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "patch-proof": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "list-artwork": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "create-artwork": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get-artwork": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "patch-artwork": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "list-return": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "create-return": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get-return": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "post-data": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get-data": {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request identifier, in the format of a GUID */
                "X-Request-ID": components["parameters"]["requestId"];
                /** @description An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
                 *     The ID will be returned in a response header. */
                "X-Correlation-ID"?: components["parameters"]["correlationId"];
            };
            path: {
                /** @description Unique identifier of this resource */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
