name: "4. PR Title Check"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

permissions:
  contents: read

jobs:
  check-pr-title:
    name: "Check PR title"
    runs-on: ubuntu-latest
    steps:
      - name: "Check PR title format"
        uses: NHSDigital/nhs-notify-shared-modules/.github/actions/check-pr-title-format@2e0290add04f46fa5c5fc816f02beeffa38f6a51 # 3.0.9
        with:
          title: ${{ github.event.pull_request.title }}
