name: "4. PR Title Check"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

permissions:
  contents: read

jobs:
  check-pr-title:
    name: "Check PR title"
    runs-on: ubuntu-latest
    steps:
      - name: "Check PR title format"
        uses: NHSDigital/nhs-notify-shared-modules/.github/actions/check-pr-title-format@5.1.3 # NOSONAR - githubactions:S7637 - internally controlled repo, pinned by tag
        with:
          title: ${{ github.event.pull_request.title }}
