name: Deploy proxy to internal-dev

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR Number for PR Environment"
        required: false

permissions:
  contents: read

jobs:
  deploy-internal-dev:
    runs-on: ubuntu-latest
    name: Deploy to Internal Dev
    env:
      PROXYGEN_API_NAME: notify-supplier-api
      PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}
      PR_NUMBER: ${{ github.event.inputs.pr_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Npm install
        working-directory: .
        run: npm ci
        shell: bash

      - name: Setup Proxy Name and target
        shell: bash
        run: |
          if [ -z $PR_NUMBER ]
          then
            echo "INSTANCE=$PROXYGEN_API_NAME" >> $GITHUB_ENV
            echo "TARGET=https://main.suppliers.dev.nhsnotify.national.nhs.uk" >> $GITHUB_ENV
            echo "SANDBOX_TAG=latest" >> $GITHUB_ENV
            echo "MTLS_NAME=notify-supplier-mtls" >> $GITHUB_ENV
          else
            echo "TARGET=https://pr$PR_NUMBER.suppliers.dev.nhsnotify.national.nhs.uk" >> $GITHUB_ENV
            echo "INSTANCE=$PROXYGEN_API_NAME-PR-$PR_NUMBER" >> $GITHUB_ENV
            echo "SANDBOX_TAG=pr$PR_NUMBER" >> $GITHUB_ENV
            echo "MTLS_NAME=notify-supplier-mtls-pr$PR_NUMBER" >> $GITHUB_ENV
          fi

      - name: Install Proxygen client
        shell: bash
        run: |
          # Install proxygen cli
          pip install pipx
          pipx install proxygen-cli

          # Setup proxygen auth and settings
          mkdir -p ${HOME}/.proxygen
          echo -n $PROXYGEN_PRIVATE_KEY | base64 --decode > ${HOME}/.proxygen/key
          envsubst < ./.github/proxygen-credentials-template.yaml > ${HOME}/.proxygen/credentials.yaml
          envsubst < ./.github/proxygen-credentials-template.yaml | cat
          envsubst < ./.github/proxygen-settings.yaml > ${HOME}/.proxygen/settings.yaml
          envsubst < ./.github/proxygen-settings.yaml | cat

      - name: Build internal dev oas
        working-directory: .
        shell: bash
        run: |
          if [ -z $PR_NUMBER ]
          then
            make build-json-oas-spec APIM_ENV=internal-dev
          else
            make build-json-oas-spec APIM_ENV=internal-dev-pr
          fi

      - name: Set target and cert
        shell: bash
        run: |
          jq --arg newurl "$TARGET" '.["x-nhsd-apim"].target.url = $newurl' build/notify-supplier.json > build/notify-supplier_target.json && mv build/notify-supplier_target.json build/notify-supplier.json
          jq --arg newmtls "$MTLS_NAME" '.["x-nhsd-apim"].target.security.secret = $newmtls' build/notify-supplier.json > build/notify-supplier_target.json && mv build/notify-supplier_target.json build/notify-supplier.json

      - name: Deploy to Internal Dev
        shell: bash
        run: |
          proxygen instance deploy internal-dev $INSTANCE build/notify-supplier.json --no-confirm
